name: quran
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  get: ^4.6.5 
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/svgs/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/applogo.png"
  min_sdk_android: 21
